name: Frontend Deploy

on:
  workflow_run:
    workflows: ["Frontend Build"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
            docker stop ${{ secrets.DOCKERHUB_USERNAME }}/frontend || true
            docker rm ${{ secrets.DOCKERHUB_USERNAME }}/frontend || true
            docker run -d --name ${{ secrets.DOCKERHUB_USERNAME }}/frontend -p 80:80 \
              -e REACT_APP_BACKEND_URL=${{ secrets.DEV_BACKEND_URL }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
            docker system prune -af
